[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
QuiverTools = "dc2e10be-62a3-4315-9c95-46bb97ac152d"
SchubertPolynomials = "ca6918c7-c46a-4663-8c75-d24c3a15490e"

[sources]
SchubertPolynomials = {url = "https://github.com/pseudoeffective/SchubertPolynomials.jl"}
