name: Format
on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'docs/make.jl'
      - '.JuliaFormatter.jl'
      - '.github/workflows/Format.yml'
  workflow_dispatch:
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/julia-format@v3
