name: Format
on:
  push:
    paths:
      - 'src/**'
      - 'ext/**'
      - 'test/**'
      - 'docs/make.jl'
      - '.JuliaFormatter.jl'
      - '.github/workflows/Format.yml'
  workflow_dispatch:
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
      - name: Install JuliaFormatter
        run: julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
      - name: Run JuliaFormatter
        run: julia .JuliaFormatter.jl
