name: tests
on: 
  push:
    branches: [ main ]
    paths:
      - "**.jl"
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout QuiverTools-julia
        uses: actions/checkout@latest
      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
      - name: Build package
        uses: julia-actions/julia-buildpkg@latest
      - name: Run tests
        uses: julia-actions/julia-runtest@latest
